### ISSUE TITLE
Error Connecting to API

### ISSUE THREAD

**Issue by dmthepm** [plecong/homebridge-dkncloudna#10]
This worked for me like a charm for the first several weeks and then one day I noticed the devices acted like they were working in homekit but it wasnt actually changing DKN. And the temp readings in homekit were wrong. 

I looked at the log and had this sudden error. 

![AFC559EB-257F-4FEF-AD04-74D1071BEB47](https://github.com/plecong/homebridge-dkncloudna/assets/39069878/0660a1d9-e65e-475c-8ca4-652372642b5b)

My wife is disappointed in me. Please help 😂

**Comment by plecong** [comment]
Hi...

Can you tell me if you configured the plugin with your email/password or just using the tokens? I've found that for some reason DKN NA will invalidate all tokens so the surest way for the plugin to reconnect is to configure it with your email/password used for the DKN NA app. 

Even then, I've noticed that my DKN NA app will be logged out and that I need to re-login on the plugin.

Please try re-authenticating and saving your email/password login information.

**Comment by dmthepm** [comment]
I validated with my email and pass. Bht noticed now that there are
tokens in the settings (which maybe my credentials converted to tokens).
I dont know how that works but didnt generate those api creds myself. 

On May 22, 2023, Andrew Ng ***@***.***> wrote:
> Hi...
>
> Can you tell me if you configured the plugin with your email/password
> or just using the tokens? I've found that for some reason DKN NA will
> invalidate all tokens so the surest way for the plugin to reconnect is
> to configure it with your email/password used for the DKN NA app.
>
> Even then, I've noticed that my DKN NA app will be logged out and that
> I need to re-login on the plugin.
>
> Please try re-authenticating and saving your email/password login
> information.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/plecong/homebridge-
dkncloudna/issues/10#issuecomment-1557960099>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AJKCRNQUXCXWLCSBRGNFAKTXHPFP3ANCNFSM6AAAAAAYJ3ZCLA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by plecong** [comment]
After entering your email/password you’ll need to click the “Authenticate” button. They fetched the tokens which are used to login in the future. Also you’ll want to check the box that says “Save login info”. This checkbox allows the plugin to login using your email/password if the tokens are invalidated.

**Comment by dmthepm** [comment]
Yeah, im sure I did this the first time. But maybe I didnt check the
save login box. I did that again and now its working. 🙏

On May 22, 2023, Andrew Ng ***@***.***> wrote:
> After entering your email/password you’ll need to click the
> “Authenticate” button. They fetched the tokens which are used to login
> in the future. Also you’ll want to check the box that says “Save login
> info”. This checkbox allows the plugin to login using your
> email/password if the tokens are invalidated.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/plecong/homebridge-
dkncloudna/issues/10#issuecomment-1558016387>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AJKCRNXD2BJ5A2CJQDS6RWTXHPJLTANCNFSM6AAAAAAYJ3ZCLA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
