### ISSUE TITLE
Feature Request: Expose Temperatures

### ISSUE THREAD

**Issue by jaredmoody** [plecong/homebridge-dkncloudna#5]
Would it be possible to expose these temperatures to homebridge? I'd like to perform automations based on them:

![Screenshot 2022-07-27 at 11 16 40](https://user-images.githubusercontent.com/27690/181344329-c83db5a0-3dc8-4b87-8cc1-6809267a43dd.png)

**Comment by plecong** [comment]
Yes, the temperature on the left of the two highlighted is already exposed as the "current temperature" on the HomeKit Thermostat service. The temperature in the middle of the dial is the "target temperature" in the HomeKit Thermostat service. 

The temperature on the right of the two highlighted looks to be the external temperature and the plugin receives that data, but there isn't another temperature setting on the HomeKit Thermostat service. If you're looking for this external temperature then I would need to add a separate Temperature Sensor service to HomeKit.

Here are two images that show the current temperature (76) and target temperature (72) between the DKN Cloud NA app and HomeKit. 

Are you looking for the external temperature?

![image](https://user-images.githubusercontent.com/164016/181406458-cba0acb5-d3c6-45b4-a909-cb39da3837ec.png)
![image](https://user-images.githubusercontent.com/164016/181406505-f55c9da1-f8b9-444d-a687-ef7086d69fbe.png)

**Comment by PhilM-IT** [comment]
Would love this for the same reason.... I'm good with a separate sensor being exposed.

**Comment by plecong** [comment]
This is now fixed as v0.2.0. The exterior temperature sensor is an accessory on the device, so you'll need to click through to "Accessory Details", scroll down to the configuration, and then select "Accessories" to view the separate sensor. From there, you should be able to create an automation.
