### ISSUE TITLE
Error Loading Plugin on HOOBS

### ISSUE THREAD

**Issue by branwall** [plecong/homebridge-dkncloudna#6]
I'm having trouble getting the plugin to load after (apparently) installing successfully on my homebridge (via the HOOBS operating system).  Even after editing the config file to add credentials, nothing changes.

I'm not sure how helpful this is, but below is the debug output I see after installing.  If any other info would be helpful, I'm happy to provide it.

(By the way, I'm super excited you decided to make this.  Thank you so much for the work you've already put in, and thanks in advance for any help you're able to provide so I can get up and running!)

8/5/2022, 7:59:58 PMyarn add v1.22.19
8/5/2022, 7:59:59 PM[1/4] Resolving packages...
8/5/2022, 8:00:04 PM[2/4] Fetching packages...
8/5/2022, 8:00:05 PM[3/4] Linking dependencies...
8/5/2022, 8:00:11 PM[4/4] Building fresh packages...
8/5/2022, 8:00:11 PMsuccess Saved lockfile.
8/5/2022, 8:00:12 PMsuccess Saved 23 new dependencies.
8/5/2022, 8:00:12 PMinfo Direct dependencies
8/5/2022, 8:00:12 PM└─ @plecong/homebridge-dkncloudna@0.1.0
8/5/2022, 8:00:12 PMinfo All dependencies
8/5/2022, 8:00:12 PM├─ @homebridge/plugin-ui-utils@0.0.19
8/5/2022, 8:00:12 PM├─ @plecong/homebridge-dkncloudna@0.1.0
8/5/2022, 8:00:12 PM├─ after@0.8.2
8/5/2022, 8:00:12 PM├─ arraybuffer.slice@0.0.7
8/5/2022, 8:00:12 PM├─ backo2@1.0.2
8/5/2022, 8:00:12 PM├─ base64-arraybuffer@0.1.4
8/5/2022, 8:00:12 PM├─ blob@0.0.5
8/5/2022, 8:00:12 PM├─ component-bind@1.0.0
8/5/2022, 8:00:12 PM├─ component-inherit@0.0.3
8/5/2022, 8:00:12 PM├─ engine.io-client@3.5.2
8/5/2022, 8:00:12 PM├─ engine.io-parser@2.2.1
8/5/2022, 8:00:12 PM├─ has-cors@1.1.0
8/5/2022, 8:00:12 PM├─ ms@2.0.0
8/5/2022, 8:00:12 PM├─ node-fetch@2.6.7
8/5/2022, 8:00:12 PM├─ socket.io-client@2.5.0
8/5/2022, 8:00:12 PM├─ socket.io-parser@3.3.2
8/5/2022, 8:00:12 PM├─ to-array@0.1.4
8/5/2022, 8:00:12 PM├─ tr46@0.0.3
8/5/2022, 8:00:12 PM├─ webidl-conversions@3.0.1
8/5/2022, 8:00:12 PM├─ whatwg-url@5.0.0
8/5/2022, 8:00:12 PM├─ ws@7.4.6
8/5/2022, 8:00:12 PM├─ xmlhttprequest-ssl@1.6.3
8/5/2022, 8:00:12 PM└─ yeast@0.1.2
8/5/2022, 8:00:12 PMDone in 13.56s.

. . . 

8/5/2022, 8:00:14 PMDkncloudna BridgeConfiguration change
8/5/2022, 8:00:14 PMdkncloudnabridge stopping
8/5/2022, 8:00:19 PMDkncloudna Bridge starting
8/5/2022, 8:00:19 PMDkncloudna Bridge starting
8/5/2022, 8:00:30 PMDkncloudna BridgeERRORError loading plugin "@plecong/homebridge-dkncloudna"
8/5/2022, 8:00:30 PMDkncloudna BridgeERRORError loading plugin "@plecong/homebridge-dkncloudna"
8/5/2022, 8:00:31 PMDkncloudna BridgeWARNINGNo plugins installed.
8/5/2022, 8:00:31 PMDkncloudna BridgeWARNINGNo plugins installed.
8/5/2022, 8:00:31 PMDkncloudna BridgeLoading 1 platforms...
8/5/2022, 8:00:31 PMDkncloudna BridgeLoading 1 platforms...
8/5/2022, 8:00:31 PMDkncloudna BridgeBridge is running on port 51896.

**Comment by plecong** [comment]
Hi! I haven’t tried running this on HOOBS, but should be able to give it an install and see what errors pop-up if any. Unfortunately I’m away from my development machine for a few days, so detailed debugging will be some time. 

Thanks for the logs, but they doesn’t seem to pinpoint the error. Are you able to restart in debug mode `hoobs -D` and see what log messages come up?

**Comment by branwall** [comment]
Sadly, not getting any more detail in "debug mode."  

What's weird is that the plugin seems to crash immediately before printing any error messages, and I have no idea why that would be the case.  From a few Google searches, I thought it could be some weird dependency requirements, but everything on my end is up to date and greater than your minimum versions in package.json.

**Comment by plecong** [comment]
Hmm. There must be some kind of interaction with HOOBS trying to load the plugin, but without more detail from HOOBS, it’ll be hard to tell. 

I’ll try to install HOOBS and the plugin and see what I get, but as I mentioned previously it’ll be a few days. Please feel free to update this issue if you’re able to get anymore logs and I can take a look in the meantime.

**Comment by branwall** [comment]
Certainly, will do! Thanks for looking into it whenever you do get a chance.

**Comment by branwall** [comment]
One thing I'll add, in case helpful:  I've uninstalled and reinstalled the plugin several times now.  I've noticed that when I add credentials to the config file, my error messages seem to duplicate, for some reason.  (This is making me even more sure it's some HOOBS issue.)

For instance, with no credentials:
8/6/2022, 8:51:08 AMDkncloudna BridgeERRORError loading plugin "@plecong/homebridge-dkncloudna"
8/6/2022, 8:51:08 AMDkncloudna BridgeWARNINGNo plugins installed.
8/6/2022, 8:51:08 AMDkncloudna BridgeLoading 1 platforms...
8/6/2022, 8:51:09 AMDkncloudna BridgeBridge is running on port 51896.


And _with_ credentials:
8/6/2022, 9:21:23 AMDkncloudna BridgeERRORError loading plugin "@plecong/homebridge-dkncloudna"
8/6/2022, 9:21:23 AMDkncloudna BridgeERRORError loading plugin "@plecong/homebridge-dkncloudna"
8/6/2022, 9:21:23 AMDkncloudna BridgeWARNINGNo plugins installed.
8/6/2022, 9:21:23 AMDkncloudna BridgeWARNINGNo plugins installed.
8/6/2022, 9:21:23 AMDkncloudna BridgeLoading 1 platforms...
8/6/2022, 9:21:23 AMDkncloudna BridgeLoading 1 platforms...
8/6/2022, 9:21:24 AMDkncloudna BridgeBridge is running on port 51896.
8/6/2022, 9:21:24 AMDkncloudna BridgeBridge is running on port 51896.

**Comment by plecong** [comment]
Just so I can replicate correctly. From your logs it appears that the plugin is in a child bridge called “Dkncloudna”. Am I reading that right?

**Comment by branwall** [comment]
Yep.  HOOBS defaults to putting each plugin in its own bridge, and it defaults to naming the bridge after the plugin.  Here's how the install process looks from the HOOBS UI:

![image](https://user-images.githubusercontent.com/6343252/183258586-74ff1b2e-bddc-4bae-9211-55977387c557.png)

**Comment by plecong** [comment]
Cool thanks for the confirmation. I don’t have any reason that would affect things, but who knows. I just picked up the Homebridge framework a couple weeks ago just for this, so can be.

**Comment by plecong** [comment]
@branwall Okay, I was about to give up on this after:

- Trying to install HOOBS on my Mac (the Darwin package doesn't seem to be allowed on my Mac)
- Trying on my home server using the [hoobs/hoobs](https://hub.docker.com/r/hoobs/hoobs Docker container (which apparently is out of date and uses an old version of both Homebridge and Node)
- Finally, installing on my RPi (against my better judgement because that's where I run my actual Homebridge). 

Once installed on RPi, I got the error above, but nothing else to show in the logs even after attempting to decipher the CLI and enabling `debug` and `verbose` flags, neither of which seem to do much from the command line. I just have to take a moment and say that the HOOBS documentation online is wildly inaccurate as they seem to have changed quite a bit (`hoobs` to `hoobsd`, logging, etc.) in the last year or so. Anywho...

Finally, after going through the HOOBS code base I see where the error is happening and just patched my local copy to print out the error. It appears that the plugin is still `require`-ing the `homebridge` library even though I'm only importing an enum. This is a warning they give you when writing plugins to not import `homebridge`, but I'm following the template and this seems to work on a straight Homebridge install. 

I've patched this on my RPi and it seems to be working correctly, so I'm going to publish a v0.1.1 to NPM. It does appear that HOOBS caches the Read Me page, but when uninstalling and re-installing it does use the latest version and it looks to be working on mine. Just put in the email and password into the configuration.

**Comment by branwall** [comment]
Thanks so much for looking into it!  Unfortunately, looks like HOOBS's servers haven't yet scraped the new version available on Github, so I can't try out 0.1.1 yet (at least, not without sideloading it--for which all the instructions I've found online are out of date).  Will report back as soon as I see the new version available!

**Comment by plecong** [comment]
Actually, give it a try by uninstalling and re-installing. The HOOBS servers don't show the updated version of the page, but if you try installing then it appears to install v0.1.1 (the version should be visible in the installation log).

**Comment by branwall** [comment]
Aha, you're right. Wow--looks like that worked perfectly! You're a lifesaver; thanks so much for fixing that so quickly (and for making this thing in the first place)! What a huge upgrade over having to use the Dkncloudna app.
