### ISSUE TITLE
Homebridge Reports Accessory is Off when Running

### ISSUE THREAD

**Issue by jaredmoody** [plecong/homebridge-dkncloudna#7]
![IMG_F4F585DC0328-1](https://user-images.githubusercontent.com/27690/192407112-e215abb4-f71a-4ac4-a0e1-7f82164ab5d3.png)

![IMG_3546E32F87B0-1](https://user-images.githubusercontent.com/27690/192407216-8c13b14c-eca6-45f9-8394-b48550295828.jpeg)

**Comment by plecong** [comment]
Thanks for reporting @jaredmoody!

A few questions:

- How was the power status changed? (DKN app, HomeKit, Homebridge, remote, other)
- Is this a persistent and/or reproducible behavior? 
- Does the power status re-sync if you restart Homebridge?
- Do other settings (like temp or mode) sync but not the power status?
- Are you able to attach any Homebridge logs? 

There are several places where syncing can get out of…sync.

**Comment by jaredmoody** [comment]
Ah, of course I didn't even think to look at the logs 🤦 

I was getting this error:

```
[dkncloudna] Error connecting to API Error: Unable to authenticate to DKN Cloud NA API
    at Api.connect (/usr/lib/node_modules/@plecong/homebridge-dkncloudna/src/api.ts:99:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I re-authenticated, then had to restart home bridge, and now is in-sync again. I'm not sure why my tokens would become invalid though.

**Comment by plecong** [comment]
Thanks for checking. The tokens expire after something like 30 days, but there’s code to detect bad tokens and try to refresh. Obviously, I wasn’t able to test this thoroughly as I’m only able to replicate certain failures against their API. The most solid setting is storing your credentials, as the fail safe is to tear it all down and start with those to log in. 

Thanks for using the plugin and reporting the issue! Btw, did you ever get the automation working based on temp? I never saw if you needed the external temp or not.

**Comment by jaredmoody** [comment]
Ah, OK, I did not have credentials stored, sounds like that will probably help.

I didn't set up my automation yet - but I would still like that external temperature exposed!
