### ISSUE TITLE
iOS 16.1 “accessory not supported”

### ISSUE THREAD

**Issue by sundar2012** [plecong/homebridge-dkncloudna#9]
I was able to add my unit to homebridge successfully and I can control it from homebridge.  However, in homekit itself (on iOS 16.1) it says the accessory is not supported and it doesn’t appear as a thermostat controller.

**Comment by plecong** [comment]
Thanks for reporting this issue. Do you have a screenshot? I just upgraded to iOS 16.1 today and the accessory is still there and working, but haven’t tried adding a fresh hub. 

Let me test this out and get back to you.

**Comment by sundar2012** [comment]
A few more details: my unit is a Daikin AC with an Airzone wifi controller that is linked to the DKN NA app (and it seems it doesn't pair with any other app like Airzone after some resets and testing).   The account authenticates in home bridge and the unit is recognized and controllable in the home bridge UI.
![IMG_EEB745F86D23-1](https://user-images.githubusercontent.com/60369965/198076221-6e67c0db-c025-4d41-92df-9365133debaa.jpeg)

**Comment by plecong** [comment]
Have you enabled the external temperature or fan services in the configuration?

**Comment by plecong** [comment]
And what version of Homebridge are you running?

**Comment by sundar2012** [comment]
Strange.  So I enabled external temp.  Restarted homebridge.  No change.  Disabled external temp.  Restarted and it showed up!  Not sure if it’s a bug with my setup or some quirk but it’s working so I’m going to close the issue.  Thank you!

**Comment by plecong** [comment]
Glad it's working, but yes, that is strange. Hope you enjoy using this!
